# Love with AI: Deep Learning for Dating {#Love-with-AI}

#### Keywords

Dating, Artificial Intelligence, Love, Romance, Deep Learning

## Dating Apps Need Improvement

Online dating has evolved into a 2-billion-dollar industry and one third of married couples in the US meet online. However, popular dating apps like Tinder and OkCupid still use simple algorithms and questionnaires to suggest potential partners. Additionally, these dating apps match people based on their shared interests and similar personalities. That's a reasonable starting point, but the truth is that people are not always attracted to people that are similar to them. Can we use data science to create a more refined version of the existing dating apps? _Love-with-AI_ is a program that leverages deep learning to learn the user’s dating preferences and make partner recommendations that are closer to the user’s “type”. 

## How the Machine Learns Love

Love-with-AI uses an artificial neural network which works like a biological neural network (i.e., the brain). Using deep learning, it learns from the user's input and millions of other cases of training data to build neural network layers that get closer and closer to successful partner recommendations. 

The program identifies patterns in both the images and the text of the bio in each profile that is liked or disliked by the user. From there, _Love-with-AI_ is able to classify the physical appearance and bio context of each potential dating partner and predict them as either “liked” or “not liked”. It then suggests partners to the user that are similar to those that he/she has liked in the past. _Love-with-AI_ also learns from the messaging content of the users within the apps. Using natural language processing, _Love-with-AI_ analyzes the conversations among users to refine its dating recommendations. The program learns a set of attractiveness characteristics from the “liked” labeled profiles and the interesting conversations and keeps refining this set every time the user uses the app. 

## You Can Find Love with AI

In order to relieve any user privacy concerns, _Love-with-AI_ asks for the user's consent to leverage the program upon signing up. For example, if Tinder buys _Love-with-AI_, its users will be asked whether they want to allow the program to access their data in order to provide better dating partner recommendations.

_Love-with-AI_ gives any dating app a competitive advantage in the online dating industry. It uses cutting edge artificial intelligence technology to help people find dating partners by learning the users’ preferences from the labeled examples. The limitation that _Love-with-AI_ faces is that it is challenging to teach a machine to perfectly understand something as old fashioned as love, but this technology comes closer by more accurately suggesting successful dating partners. Some people are attracted to similars and some are attracted to opposites - either way, _Love-with-AI_ is able to learn people’s attractiveness patterns and make suggestions accordingly. 
